name: Build ESP-IDF Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32 
        path: /ESP32_webserver
        commands: |
         idf.py fullclean
         idf.py clean
         idf.py build
