name: Build ESP-IDF Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4 
        path: /ESP32_webserver
        target: esp32
        command: |
           idf.py fullclean
           idf.py clean
           idf.py build
           
    - name: Build and show result
      uses: batov/esp32_qemu_runner@v4.3
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
            files: report.xml
   


