name: Build ESP-IDF Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ESP-IDF
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools python3-serial python3-click python3-cryptography python3-future python3-pyparsing python3-pyelftools cmake ninja-build ccache libffi-dev libssl-dev dfu-util
        pip install pyparsing==2.3.4 idf-component-manager==0.2.99 gdbgui==0.13.2.0 pygdbmi==0.9.0.2 python-socketio<5 kconfiglib==13.7.1 reedsolo==1.5.3 bitstring==3.1.6 ecdsa==0.16.0 construct==2.10.54

        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        git checkout v4.4
        ./install.sh
        export IDF_PATH=$(pwd)
        source export.sh

    - name: Build Project
       
      run: |
        
        $IDF_PATH/tools/idf.py build

